name: 'Code Workflow'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Strapi
        env:
          EC2_USER: ubuntu
          SAIPAVAN_EC2_HOST: ${{ secrets.SAIPAVAN_EC2_HOST }}
          SAIPAVAN_EC2_KEY: ${{ secrets.SAIPAVAN_EC2_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $SAIPAVAN_EC2_KEY $EC2_USER@$SAIPAVAN_EC2_HOST "
            cd /srv/strapi
            git pull origin main
            npm install
            pm2 restart strapi
          "

