name: 'Code Workflow'

on:
  push:
    branches:
      - saipavan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Strapi
        env:
          EC2_USER: ubuntu
          SAIPAVAN_EC2_HOST: ${{ secrets.SAIPAVAN_EC2_HOST }}
          SAIPAVAN_EC2_KEY: ${{ secrets.SAIPAVAN_EC2_KEY }}
        run: |
          echo "${SAIPAVAN_EC2_KEY}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$SAIPAVAN_EC2_HOST "
            cd /srv/strapi
            git pull origin saipavan
            npm install
            pm2 restart strapi
          "

